# Config file for automatic testing at travis-ci.org
dist: trusty
language: python
python: 3.5
cache: pip
env:
  - TOX_ENV=py35

install:
  - pip install -U tox
  - pip install -U coveralls

script:
  - tox -e $TOX_ENV
  - python setup.py install

after_script:
  - coveralls

matrix:
  include:
    - python: 3.6
      env:
        - TOX_ENV=py36
