# Config file for automatic testing at travis-ci.org

language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=pypy

install:
  - pip install -U tox
  - pip install -U coveralls

script:
  - tox -e $TOX_ENV
  - python setup.py install

after_script:
  - coveralls

matrix:
  include:
    - python: 3.6
      env:
        - TOX_ENV=py36
