# -*- coding: utf-8 -*-
"""auto generated by script at 2017-08-20 09:33:46.650872.

don't edit it.

"""
from typing import Any

from attr import NOTHING

from aiobearychat.abc import API
from aiobearychat.sansio import Response, clean_nothing_keys


class EmojiAPI(API):
    """团队自定义 emoji 相关 API."""

    async def list(self,
                   **requester_params: Any) -> Response:
        """返回团队内的自定义 emoji 列表.

        官方文档地址：https://github.com/bearyinnovative/OpenAPI/blob/master/api/emoji.list.md



        :return: response. 一个 :class:`aiobearychat.sansio.Response` 实例

        ``response.body`` 返回值示例::

            response.status 等于 200 时:

                [
                  {
                    "id": "=bw52O",
                    "uid": "=bw52O",
                    "team_id": "=bw52O",
                    "name": "hello",
                    "type": "emoji",
                    "created": "2017-03-13T13:54:16.000+0000",
                    "updated": "2017-03-13T13:54:16.000+0000",
                    "url": "http://example.com/1.jpg"
                  }
                ]

        """
        url_params = {}
        body_params = {}
        url_params['token'] = self._token

        url_params.update({
        })

        url = self.base_url + '/emoji.list'
        headers = {
            'content-type': 'application/json',
        }

        url_params = clean_nothing_keys(url_params)
        body_params = clean_nothing_keys(body_params)

        return await self._make_request('get',
                                        url,
                                        url_params=url_params,
                                        body_params=body_params,
                                        headers=headers,
                                        )
