# -*- coding: utf-8 -*-
"""auto generated by script at 2017-08-20 14:27:17.621320.

don't edit it.

"""
from typing import Any

from attr import NOTHING

from aiobearychat.abc import API
from aiobearychat.sansio import Response, clean_nothing_keys


class StickerAPI(API):
    """团队 sticker 相关 API."""

    async def list(self,
                   **requester_params: Any) -> Response:
        """返回当前用户的自定义 sticker 列表.

        官方文档地址：https://github.com/bearyinnovative/OpenAPI/blob/master/api/sticker.list.md



        :return: response. 一个 :class:`aiobearychat.sansio.Response` 实例

        ``response.body`` 返回值示例::

            response.status 等于 200 时:

                [
                  {
                    "pack": "黑白熊静态",
                    "stickers": [
                      {
                        "url": "https://dn-bearychat.qbox.me/sticker-gif-20.gif",
                        "name": "累",
                        "width": 240,
                        "height": 240
                      }
                    ]
                  }
                ]

        """
        url_params = {}
        body_params = {}
        url_params['token'] = self._token

        url_params.update({
        })

        url = self.base_url + '/sticker.list'
        headers = {
            'content-type': 'application/json',
        }

        url_params = clean_nothing_keys(url_params)
        body_params = clean_nothing_keys(body_params)

        return await self._make_request('get',
                                        url,
                                        url_params=url_params,
                                        body_params=body_params,
                                        headers=headers,
                                        )
